version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Test test test
          command: |
            echo "I'm testing!"
            sleep 60
            if [[ -n "${FAIL_THE_QUEUE}" ]]; then
              echo "uh oh, we're gonna fail!"
              exit 1
            fi
            echo "Ok! All tested!"
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Ready to publish?
          command: |
            echo "Publish me!"

workflows:
  commit:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
      - publish:
          requires:
            - test
          filters:
            branches:
              only: bors-mq/staging
